# Generated by Django 5.1.5 on 2025-03-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duty_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPDM2.camp')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPDM2.volunteer')),
            ],
        ),
    ]
