# Generated by Django 5.1.5 on 2025-03-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0003_emergency_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='emergency_photos/')),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('panchayat', models.CharField(max_length=50)),
                ('missing_date', models.DateField()),
                ('missing_place', models.CharField(max_length=100)),
                ('other_details', models.CharField(max_length=100)),
            ],
        ),
    ]
