# Generated by Django 5.1.5 on 2025-03-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0004_missing_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_person',
            name='public_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DPDM2.public'),
            preserve_default=False,
        ),
    ]
