# Generated by Django 5.1.5 on 2025-03-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0005_missing_person_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_category', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('missing_date', models.DateField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPDM2.missing_vehicle')),
            ],
        ),
    ]
