# Generated by Django 5.1.5 on 2025-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0006_missing_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_vehicle',
            name='vehicle_number',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
