# Generated by Django 5.1.5 on 2025-03-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0007_missing_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missing_vehicle',
            name='station_id',
        ),
        migrations.AddField(
            model_name='missing_vehicle',
            name='public_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DPDM2.public'),
            preserve_default=False,
        ),
    ]
