# Generated by Django 5.1.5 on 2025-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0009_missing_vehicle_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_person',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
