# Generated by Django 5.1.5 on 2025-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0010_missing_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_vehicle',
            name='update_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
