# Generated by Django 5.1.5 on 2025-03-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0011_missing_vehicle_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missing_vehicle',
            name='update_status',
        ),
    ]
