# Generated by Django 5.1.5 on 2025-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0012_remove_missing_vehicle_update_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
