# Generated by Django 5.1.5 on 2025-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0013_vehicleinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('panchayat', models.CharField(max_length=50)),
                ('taluk', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
                ('building_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='house_photos/')),
                ('state', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleInsurance',
        ),
    ]
