# Generated by Django 5.1.5 on 2025-04-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0015_rename_fund_allocation_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='public_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DPDM2.public'),
            preserve_default=False,
        ),
    ]
