# Generated by Django 5.1.5 on 2025-04-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0016_fund_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='in_camp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='panchayat',
            field=models.CharField(max_length=100),
        ),
    ]
