# Generated by Django 5.1.5 on 2025-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0017_fund_account_holder_name_fund_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='ifsc_code',
            new_name='IFSC_code',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='account_holder_name',
            new_name='account_Holder_name',
        ),
        migrations.AlterField(
            model_name='fund',
            name='in_camp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
