# Generated by Django 5.1.5 on 2025-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0018_rename_ifsc_code_fund_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
