# Generated by Django 5.1.5 on 2025-04-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0019_fund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_id', models.IntegerField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPDM2.camp')),
            ],
        ),
    ]
