# Generated by Django 5.1.5 on 2025-04-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0020_assign_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_fund',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
