# Generated by Django 5.1.5 on 2025-04-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0022_alter_assign_fund_fund_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_fund',
            old_name='status',
            new_name='approve_status',
        ),
    ]
