# Generated by Django 5.1.5 on 2025-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0023_rename_status_assign_fund_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_fund',
            name='admin_status',
            field=models.IntegerField(default=0),
        ),
    ]
