# Generated by Django 5.1.5 on 2025-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0024_assign_fund_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
