# Generated by Django 5.1.5 on 2025-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0025_fund_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=20)),
                ('expiry', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
