# Generated by Django 5.1.5 on 2025-05-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0026_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='person',
            new_name='name',
        ),
    ]
