# Generated by Django 5.1.5 on 2025-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0027_rename_person_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expiry',
            new_name='month',
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
