# Generated by Django 5.1.5 on 2025-05-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0028_rename_expiry_payment_month_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_fund',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='fund',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DPDM2.fund'),
            preserve_default=False,
        ),
    ]
