# Generated by Django 5.1.5 on 2025-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0029_assign_fund_payment_status_payment_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_fund',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='fund',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
