# Generated by Django 5.1.5 on 2025-05-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0030_remove_assign_fund_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fund',
        ),
    ]
