# Generated by Django 5.1.5 on 2025-05-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0031_remove_payment_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='payment_status',
        ),
    ]
