# Generated by Django 5.1.5 on 2025-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0032_remove_fund_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
