# Generated by Django 5.1.5 on 2025-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0033_fund_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
