# Generated by Django 5.1.5 on 2025-05-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0034_emergency_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_camp',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emergency_station',
            name='message',
            field=models.TextField(),
        ),
    ]
