# Generated by Django 5.1.5 on 2025-05-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0035_alter_emergency_camp_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='authentication',
        ),
    ]
