# Generated by Django 5.1.5 on 2025-05-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0038_duty_assignment_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty_assignment',
            old_name='completed',
            new_name='complete',
        ),
    ]
