# Generated by Django 5.1.5 on 2025-05-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0039_rename_completed_duty_assignment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty_assignment',
            name='complete',
        ),
    ]
